### ISSUE TITLE
Converting circular structure to JSON error in NodeJS 18

### ISSUE THREAD

**Issue by einhaus** [Sainglend/tda-api-client#18]
TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at /var/www/node-backend/node_modules/tda-api-client/tdapiinterface.js:284:84
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)

**Comment by alvinycheung** [comment]
Same
```
/app/node_modules/.pnpm/tda-api-client@2.1.3/node_modules/tda-api-client/tdapiinterface.js:284
                    rej(`The request was made but no response was received: ${JSON.stringify(error.request)}`);
                                                                                   ^

TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'TLSSocket'
    |     property '_httpMessage' -> object with constructor 'ClientRequest'
    --- property 'socket' closes the circle
    at JSON.stringify (<anonymous>)
    at .../node_modules/.pnpm/tda-api-client@2.1.3/node_modules/tda-api-client/tdapiinterface.js:284:84
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
